In [1]:
import numpy as np
import pandas as pd

There are four collection data types in the Python programming language:

1) List is a collection which is indexed and ordered(meaning, The elements have a defined order. )
d= [11,2,3,]

2) Tuple is a collection which is ordered and unchangeable. Allows duplicate members. It is represented by parentheses.
    a = (1,2,3,4)

3) Set is a collection which is unordered and unindexed. No duplicate members.It is represented by by curly({) bracket.
    b=  {1,2,3,4,}
    Frozen Sets Frozen sets are immutable objects that only support methods and operators that produce a result without     a?ecting the frozen set or sets to which they are applied.
    frozen_set = frozenset(["e", "f", "g"]) 

4) Dictionary is a collection which is unordered, changeable and indexed. No duplicate members.It is represented by curly({) bracket.
    c=  {"A":34,"B":33}
    

http://www.thelearningpoint.net/computer-science/learning-python-programming-and-data-structures/learning-python-programming-and-data-structures--tutorial-4--built-in-data-structures-strings-lists-tuples-dictionaries-mutability

Tuples are fixed size in nature whereas lists are dynamic.
In other words, a tuple is immutable whereas a list is mutable.

You can't add elements to a tuple. Tuples have no append or extend method.
You can't remove elements from a tuple. Tuples have no remove or pop method.
You can find elements in a tuple, since this doesn’t change the tuple.
You can also use the in operator to check if an element exists in the tuple.
Tuples are faster than lists. If you're defining a constant set of values and all you're ever going to do with it is iterate through it, use a tuple instead of a list.

It makes your code safer if you “write-protect” data that does not need to be changed. Using a tuple instead of a list is like having an implied assert statement that this data is constant, and that special thought (and a specific function) is required to override that.

Some tuples can be used as dictionary keys (specifically, tuples that contain immutable values like strings, numbers, and other tuples). Lists can never be used as dictionary keys, because lists are not immutable.

Source: Dive into Python 

<b>Python tuples and lists are ordered, but dictionaries and sets are not ordered</b>  
if you put a few key/value pairs into a dictionary, they won't be in the order you added them, whereas new values would be appended to the end of lists/tuples as you add them. 

make a dictionary of a couple name/age pairs or something simple, then try printing out every item in the dict you made; try the same thing with a list of anything

# List Operations

In [158]:
arr = list()
# or simply
arr = []
arr = [1,2,3]
print(arr[0])
# result is 1
print (arr[0] + arr[1] + arr[2])
# result is 6
List = ['GeeksForGeeks'] 
print("\nList with the use of String: ") 
print(List) 
List = list('GeeksForGeeks')
print("\nList with the use of in built list function: ") 
print(List) 

1
6

List with the use of String: 
['GeeksForGeeks']

List with the use of in built list function: 
['G', 'e', 'e', 'k', 's', 'F', 'o', 'r', 'G', 'e', 'e', 'k', 's']


Elements can be added to the List by using built-in append() function. Only one element at a time can be added to the list by using append() method, for addition of multiple elements with the append() method, loops are used. 
append() method only works for addition of elements at the end of the List, for addition of element at the desired position, insert() method is used.  
Unlike append() which takes only one argument, insert() method requires two arguments(position, value). Other than append() and insert() methods,  
extend(), this method is used to add multiple elements at the same time at the end of the list.


In [126]:
#Adds a single element x to the end of a list.
print("Original list:",arr)
arr.append(9) 
print("Appending 9:", arr)
#Merges another list L to the end.
arr.extend([10,11])
print("Extend [10,11]:",arr)
#Inserts element x at position i.
arr.insert(3,77)
print("Insert 77 at index 3:",arr)
#Removes the first occurrence of element x.
arr.remove(9)
print("Remove 9:",arr)
#Removes the last element of a list. If an argument is passed, that index item is popped out.
print("Pop the last element out:",arr.pop())
#Returns the first index of a value in the list. Throws an error if it's not found.
print("First Index of a value in list :",arr.index(3))
#Counts the number of occurrences of an element x.
print("Count the occurance of an element in list",arr.count(77))
#Sorts the list.
arr.sort()
print("Sort:",arr)
#Reverses the list.
arr.reverse()
print("Reverse:", arr)
print("another way to reverse the list",arr[::-1])

Original list: [77, 77, 11, 10, 10, 3, 2]
Appending 9: [77, 77, 11, 10, 10, 3, 2, 9]
Extend [10,11]: [77, 77, 11, 10, 10, 3, 2, 9, 10, 11]
Insert 77 at index 3: [77, 77, 11, 77, 10, 10, 3, 2, 9, 10, 11]
Remove 9: [77, 77, 11, 77, 10, 10, 3, 2, 10, 11]
Pop the last element out: 11
First Index of a value in list : 6
Count the occurance of an element in list 3
Sort: [2, 3, 10, 10, 10, 11, 77, 77, 77]
Reverse: [77, 77, 77, 11, 10, 10, 10, 3, 2]
another way to reverse the list [2, 3, 10, 10, 10, 11, 77, 77, 77]


In [128]:
li=[1,6,9,22,31,42,54,908,658,4,785,95]
[len(str(li[i])) for i in range(len(li))]

[1, 1, 1, 2, 2, 2, 2, 3, 3, 1, 3, 2]

In [124]:
print(26 % 7) #(you will get remainder)

print(26 / 7) #(you will get divisor can be float value )

print(26 // 7) #(you will get divisor only integer value) )

5
3.7142857142857144
3


# List Comprehensions vs Generator Expressions

In [130]:
list_comprehension = [i for i in range(11) if i % 2 == 0] 
print(list_comprehension)

[0, 2, 4, 6, 8, 10]


generator expression: syntax difference is paranthesis vs square bracket

In [133]:
generator_expression = (i for i in range(11) if i % 2 == 0)  
print(generator_expression) 
for i in generator_expression: 
    print(i, end=" ") 

<generator object <genexpr> at 0x000001A90E93A518>
0 2 4 6 8 10 

So what’s the difference between Generator Expressions and List Comprehensions?
The generator yields one item at a time and generates item only when in demand. Whereas, in a list comprehension, Python reserves memory for the whole list. Thus we can say that the generator expressions are memory efficient than the lists.  <br> Generator expression are faster and memory efficient

# Sets

<b>In Python, Set is an unordered and unindex collection of data type that is iterable, mutable and has no duplicate elements</b>.  Set in Python is equivalent to sets in mathematics. The order of elements in a set is undefined though it may consist of various elements. Elements of a set can be added and deleted, elements of the set can be iterated, various standard operations (union, intersection, difference) can be performed on sets. Besides that, the major advantage of using a set, as opposed to a list, is that it has a highly optimized method for checking whether a specific element is contained in the set.

You cannot access items in a set by referring to an index, since sets are unordered the items has no index.

But you can loop through the set items using a for loop, or ask if a specified value is present in a set, by using the in keyword.  
Once a set is created, you cannot change its items, but you can add new items.

In [194]:
myset = {1, 2} # Directly assigning values to a set
myset = set()  # Initializing a set
myset = set(['a', 'b']) # Creating a set from a list
frozen_set = frozenset(["e", "f", "g"]) 
myset

{'a', 'b'}

<b>Frozen sets</b> in Python are immutable objects that only support methods and operators that produce a result without affecting the frozen set or sets to which they are applied. While elements of a set can be modified at any time, elements of the frozen set remain the same after creation.

## MODIFYING SETS

add() function  
adds an individual element to the set  
cannot work with an iterable, unless it is hashable.

In [197]:
myset.add('c')
myset
myset.add('a') # As 'a' already exists in the set, nothing happens
myset.add((5, 4))
myset
myset.pop()
# See below the way elements are added is not same as the way they are printed. that is why they are unordered

'b'

update() function  
you can pass multiple iterables to it and it will iterate all iterables and will include the individual elements in the set. Remember: It can accept only iterables

In [9]:
myset.update([1, 2, 3, 4]) # update() only works for iterable objects
print(myset)
myset.update({1, 7, 8})
print(myset)
myset.update({1, 6}, [5, 13])
print(myset)

{1, (5, 4), 2, 3, 4, 'c', 'a', 'b'}
{1, (5, 4), 2, 3, 4, 7, 8, 'c', 'a', 'b'}
{1, (5, 4), 2, 3, 4, 6, 7, 8, 'c', 5, 13, 'a', 'b'}


In [11]:
a = {2, 4, 5, 9}
b = {2, 4, 11, 12}
print(a.union(b)) # Values which exist in a or b
print(a.intersection(b)) # Values which exist in a and b
print(a.difference(b)) # Values which exist in a but not in b

{2, 4, 5, 9, 11, 12}
{2, 4}
{9, 5}


In [209]:
# Python program to demonstrate working# of 
# Set in Python 

# Creating two sets 
set1 = set() 
set2 = set() 

# Adding elements to set1 
for i in range(1, 6): 
	set1.add(i) 

# Adding elements to set2 
for i in range(3, 8): 
	set2.add(i) 

print("Set1 = ", set1) 
print("Set2 = ", set2) 
print("\n") 

# Union of set1 and set2 
set3 = set1 | set2# set1.union(set2) 
print("Union of Set1 & Set2: Set3 = ", set3) 

# Intersection of set1 and set2 
set4 = set1 & set2# set1.intersection(set2) 
print("Intersection of Set1 & Set2: Set4 = ", set4) 
print("\n") 

# Checking relation between set3 and set4 
if set3 > set4: # set3.issuperset(set4) 
	print("Set3 is superset of Set4") 
elif set3 < set4: # set3.issubset(set4) 
	print("Set3 is subset of Set4") 
else : # set3 == set4 
	print("Set3 is same as Set4") 

# displaying relation between set4 and set3 
if set4 < set3: # set4.issubset(set3) 
	print("Set4 is subset of Set3") 
	print("\n") 

# difference between set3 and set4 
set5 = set3 - set4 
print("Elements in Set3 and not in Set4: Set5 = ", set5) 
print("\n") 

# checkv if set4 and set5 are disjoint sets 
if set4.isdisjoint(set5): 
	print("Set4 and Set5 have nothing in common\n") 

# Removing all the values of set5 
set5.clear() 

print("After applying clear on sets Set5: ") 
print("Set5 = ", set5)

print("Set1 {} and Set2 {}".format(set1,set2))
#print("Set difference {} and difference_update {}".format(set1.difference(set2), set1.difference_update(set2)))
print("After Difference Set1 {} and Set2 {}".format(set1,set2))

# The symmetric difference of two sets A and B is the set of elements which are in either of the sets A or B 
#but not in both.
print("set Symmetric difference {} and Symmetric difference_update {}"
      .format(set1.symmetric_difference(set2), set1.symmetric_difference_update(set2)))
print("After Difference Set1 {} and Set2 {}".format(set1,set2))

Set1 =  {1, 2, 3, 4, 5}
Set2 =  {3, 4, 5, 6, 7}


Union of Set1 & Set2: Set3 =  {1, 2, 3, 4, 5, 6, 7}
Intersection of Set1 & Set2: Set4 =  {3, 4, 5}


Set3 is superset of Set4
Set4 is subset of Set3


Elements in Set3 and not in Set4: Set5 =  {1, 2, 6, 7}


Set4 and Set5 have nothing in common

After applying clear on sets Set5: 
Set5 =  set()
Set1 {1, 2, 3, 4, 5} and Set2 {3, 4, 5, 6, 7}
After Difference Set1 {1, 2, 3, 4, 5} and Set2 {3, 4, 5, 6, 7}
set Symmetric difference {1, 2, 6, 7} and Symmetric difference_update None
After Difference Set1 {1, 2, 6, 7} and Set2 {3, 4, 5, 6, 7}


## Strings 

In Python, Strings are arrays of bytes representing Unicode characters. However, Python does not have a character data type, a single character is simply a string with a length of 1. Square brackets can be used to access elements of the string.

String in single quotes cannot hold any other single quoted character in it otherwise an error arises because the compiler won’t recognize where to start and end the string. To overcome this error, use of double quotes is preferred, because it helps in creation of Strings with single quotes in them. For strings which contain Double quoted words in them, use of triple quotes is suggested. Along with this, triple quotes also allow the creation of multiline strings.

In [134]:
# Creating a String  
# with single Quotes 
String1 = 'Welcome to the Geeks World'
print("String with the use of Single Quotes: ") 
print(String1) 
  
# Creating a String 
# with double Quotes 
String1 = "I'm a Geek"
print("\nString with the use of Double Quotes: ") 
print(String1) 
  
# Creating a String 
# with triple Quotes 
String1 = '''I'm a Geek and I live in a world of "Geeks"'''
print("\nString with the use of Triple Quotes: ") 
print(String1) 
  
# Creating String with triple 
# Quotes allows multiple lines 
String1 = '''Geeks 
            For 
            Life'''
print("\nCreating a multiline String: ") 
print(String1) 

String with the use of Single Quotes: 
Welcome to the Geeks World

String with the use of Double Quotes: 
I'm a Geek

String with the use of Triple Quotes: 
I'm a Geek and I live in a world of "Geeks"

Creating a multiline String: 
Geeks 
            For 
            Life


In [142]:
String1[-4:],String1[:4]

('Life', 'Geek')

In Python, <b>Updation or deletion of characters from a String is not allowed</b>. This will cause an error because item assignment or item deletion from a String is not supported. Although deletion of entire String is possible with the use of a built-in del keyword. This is because Strings are immutable, hence elements of a String cannot be changed once it has been assigned. Only new strings can be reassigned to the same name.

While printing Strings with single and double quotes in it causes SyntaxError because String already contains Single and Double Quotes and hence cannot be printed with the use of either of these. Hence, to print such a String either Triple Quotes are used or Escape sequences are used to print such Strings.
Escape sequences start with a backslash and can be interpreted differently. If single quotes are used to represent a string, then all the single quotes present in the string must be escaped and same is done for Double Quotes.

In [143]:
# Initial String 
String1 = '''I'm a "Geek"'''
print("Initial String with use of Triple Quotes: ") 
print(String1) 
  
# Escaping Single Quote  
String1 = 'I\'m a "Geek"'
print("\nEscaping Single Quote: ") 
print(String1) 
  
# Escaping Doule Quotes 
String1 = "I'm a \"Geek\""
print("\nEscaping Double Quotes: ") 
print(String1) 
  
# Printing Paths with the  
# use of Escape Sequences 
String1 = "C:\\Python\\Geeks\\"
print("\nEscaping Backslashes: ") 
print(String1) 

Initial String with use of Triple Quotes: 
I'm a "Geek"

Escaping Single Quote: 
I'm a "Geek"

Escaping Double Quotes: 
I'm a "Geek"

Escaping Backslashes: 
C:\Python\Geeks\


In [145]:
# Python Program for 
# Formatting of Strings 

# Default order 
String1 = "{} {} {}".format('Geeks', 'For', 'Life') 
print("Print String in default order: ") 
print(String1) 

# Positional Formatting 
String1 = "{1} {0} {2}".format('Geeks', 'For', 'Life') 
print("\nPrint String in Positional order: ") 
print(String1) 

# Keyword Formatting 
String1 = "{l} {f} {g}".format(g = 'Geeks', f = 'For', l = 'Life') 
print("\nPrint String in order of Keywords: ") 
print(String1) 

# Formatting of Integers 
String1 = "{0:b}".format(16) 
print("\nBinary representation of 16 is ") 
print(String1) 

# Formatting of Floats 
String1 = "{0:e}".format(165.6458) 
print("\nExponent representation of 165.6458 is ") 
print(String1) 

# Rounding off Integers 
String1 = "{0:.2f}".format(1/6) 
print("\n one-sixth is : ") 
print(String1) 

# String alignment 
String1 = "|{:<10}|{:^10}|{:>10}|".format('Geeks','for','Geeks') 
print("\nLeft, center and right alignment with Formatting: ") 
print(String1) 


Print String in default order: 
Geeks For Life

Print String in Positional order: 
For Geeks Life

Print String in order of Keywords: 
Life For Geeks

Binary representation of 16 is 
10000

Exponent representation of 165.6458 is 
1.656458e+02

 one-sixth is : 
0.17

Left, center and right alignment with Formatting: 
|Geeks     |   for    |     Geeks|


## Tuples 

Tuple is a collection of Python objects much like a list. The sequence of values stored in a tuple can be of any type, and they are indexed by integers. The important difference between a list and a tuple is that tuples are immutable. Also, Tuples are hashable whereas lists are not.

In Python, tuples are created by placing sequence of values separated by ‘comma’ with or without the use of parentheses for grouping of data sequence. Tuples can contain any number of elements and of any datatype (like strings, integers, list, etc.). Tuples can also be created with a single element, but it is a bit tricky. Having one element in the parentheses is not sufficient, there must be a trailing ‘comma’ to make it a tuple.

In [190]:
t = 1,2,3,4,4
tt = (1,2,3,4,4 )
ttt = tuple((1,2,3,4,55)) # use the double brackets for inbuilt function otherwise it will throw an error
print(type(t), t)
print(type(tt), tt)
print(type(ttt), ttt)

<class 'tuple'> (1, 2, 3, 4, 4)
<class 'tuple'> (1, 2, 3, 4, 4)
<class 'tuple'> (1, 2, 3, 4, 55)


In [157]:
# Python program to demonstrate 
# Addition of elements in a Set 

# Creating an empty tuple 
Tuple1 = () 
print("Initial empty Tuple: ") 
print (Tuple1) 

# Creating a Tuple with 
# the use of Strings 
Tuple1 = ('Geeks', 'For') 
print("\nTuple with the use of String: ") 
print(Tuple1) 

# Creating a Tuple with 
# the use of list 
list1 = [1, 2, 4, 5, 6] 
print("\nTuple using List: ") 
print(tuple(list1)) 

# Creating a Tuple 
# with the use of loop 
Tuple1 = ('Geeks') 
n = 5
print("\nTuple with a loop") 
for i in range(int(n)): 
	Tuple1 = (Tuple1,) #there must be a trailing ‘comma’ to make it a tuple
	print(Tuple1) 

# Creating a Tuple with the 
# use of built-in function 
Tuple1 = tuple('Geeks') 
print("\nTuple with the use of function: ") 
print(Tuple1) 

# Creating a Tuple with 
# Mixed Datatypes 
Tuple1 = (5, 'Welcome', 7, 'Geeks') 
print("\nTuple with Mixed Datatypes: ") 
print(Tuple1) 

# Creating a Tuple 
# with nested tuples 
Tuple1 = (0, 1, 2, 3) 
Tuple2 = ('python', 'geek') 
Tuple3 = (Tuple1, Tuple2) 
print("\nTuple with nested tuples: ") 
print(Tuple3) 

# Creating a Tuple 
# with repetition 
Tuple1 = ('Geeks',) * 3
print("\nTuple with repetition: ") 
print(Tuple1) 


Initial empty Tuple: 
()

Tuple with the use of String: 
('Geeks', 'For')

Tuple using List: 
(1, 2, 4, 5, 6)

Tuple with a loop
('Geeks',)
(('Geeks',),)
((('Geeks',),),)
(((('Geeks',),),),)
((((('Geeks',),),),),)

Tuple with the use of function: 
('G', 'e', 'e', 'k', 's')

Tuple with Mixed Datatypes: 
(5, 'Welcome', 7, 'Geeks')

Tuple with nested tuples: 
((0, 1, 2, 3), ('python', 'geek'))

Tuple with repetition: 
('Geeks', 'Geeks', 'Geeks')


In [163]:
tt.count(4), tt.index(4)

(2, 3)

Concatenation of tuple is the process of joining of two or more Tuples. Concatenation is done by the use of ‘+’ operator. Concatenation of tuples is done always from the end of the original tuple. Other arithmetic operations do not apply on Tuples.

In [164]:
t+tt

(1, 2, 3, 4, 4, 1, 2, 3, 4, 4)

In [165]:
# Slicing of a Tuple 
# with Numbers 
Tuple1 = tuple('GEEKSFORGEEKS') 
  
# Removing First element 
print("Removal of First Element: ") 
print(Tuple1[1:]) 
  
# Reversing the Tuple  
print("\nTuple after sequence of Element is reversed: ") 
print(Tuple1[::-1]) 
  
# Printing elements of a Range 
print("\nPrinting elements between Range 4-9: ") 
print(Tuple1[4:9]) 

Removal of First Element: 
('E', 'E', 'K', 'S', 'F', 'O', 'R', 'G', 'E', 'E', 'K', 'S')

Tuple after sequence of Element is reversed: 
('S', 'K', 'E', 'E', 'G', 'R', 'O', 'F', 'S', 'K', 'E', 'E', 'G')

Printing elements between Range 4-9: 
('S', 'F', 'O', 'R', 'G')


<b>Tuples are immutable and hence they do not allow deletion of a part of it. Entire tuple gets deleted by the use of del() method.</b>

In [170]:
[(i,j) for i,j in enumerate(tt)]

[(0, 1), (1, 2), (2, 3), (3, 4), (4, 4)]

In [176]:
sorted(tt,reverse=True)

[4, 4, 3, 2, 1]

In [6]:
t = set([1,2,3,4,5])
for i in range(len(t)):
    print(t[i])

TypeError: 'set' object does not support indexing

## Dictionary 

Dictionary in Python is an unordered collection of data values, used to store data values like a map, which unlike other Data Types that hold only single value as an element, Dictionary holds key:value pair. Key value is provided in the dictionary to make it more optimized. Each key-value pair in a Dictionary is separated by a colon :, whereas each key is separated by a ‘comma’.

A Dictionary in Python works similar to the Dictionary in a real world. Keys of a Dictionary must be unique and of immutable data type such as Strings, Integers and tuples, but the key-values can be repeated and be of any type.

In [210]:
# Creating an empty Dictionary 
Dict = {} 
print("Empty Dictionary: ") 
print(Dict) 
  
# Adding elements one at a time 
Dict[0] = 'Geeks'
Dict[2] = 'For'
Dict[3] = 1
print("\nDictionary after adding 3 elements: ") 
print(Dict) 
  
# Adding set of values  
# to a single Key 
Dict['Value_set'] = 2, 3, 4
print("\nDictionary after adding 3 elements: ") 
print(Dict) 
  
# Updating existing Key's Value 
Dict[2] = 'Welcome'
print("\nUpdated key value: ") 
print(Dict) 
  
# Adding Nested Key value to Dictionary 
Dict[5] = {'Nested' :{'1' : 'Life', '2' : 'Geeks'}} 
print("\nAdding a Nested Key: ") 
print(Dict) 

Empty Dictionary: 
{}

Dictionary after adding 3 elements: 
{0: 'Geeks', 2: 'For', 3: 1}

Dictionary after adding 3 elements: 
{0: 'Geeks', 2: 'For', 3: 1, 'Value_set': (2, 3, 4)}

Updated key value: 
{0: 'Geeks', 2: 'Welcome', 3: 1, 'Value_set': (2, 3, 4)}

Adding a Nested Key: 
{0: 'Geeks', 2: 'Welcome', 3: 1, 'Value_set': (2, 3, 4), 5: {'Nested': {'1': 'Life', '2': 'Geeks'}}}


In [211]:
# accesing a element from a Dictionary  
  
# Creating a Dictionary  
Dict = {1: 'Geeks', 'name': 'For', 3: 'Geeks'} 
  
# accessing a element using key 
print("Acessing a element using key:") 
print(Dict['name']) 
  
# accessing a element using key 
print("Acessing a element using key:") 
print(Dict[1]) 
  
# accessing a element using get() 
# method 
print("Acessing a element using get:") 
print(Dict.get(3)) 

Acessing a element using key:
For
Acessing a element using key:
Geeks
Acessing a element using get:
Geeks


In [212]:
# Initial Dictionary 
Dict = { 5 : 'Welcome', 6 : 'To', 7 : 'Geeks', 
        'A' : {1 : 'Geeks', 2 : 'For', 3 : 'Geeks'}, 
        'B' : {1 : 'Geeks', 2 : 'Life'}} 
print("Initial Dictionary: ") 
print(Dict) 
  
# Deleting a Key value 
del Dict[6] 
print("\nDeleting a specific key: ") 
print(Dict) 
  
# Deleting a Key from 
# Nested Dictionary 
del Dict['A'][2] 
print("\nDeleting a key from Nested Dictionary: ") 
print(Dict) 
  
# Deleting a Key  
# using pop() 
Dict.pop(5) 
print("\nPopping specific element: ") 
print(Dict) 
  
# Deleting a Key 
# using popitem() 
Dict.popitem() 
print("\nPops first element: ") 
print(Dict) 
  
# Deleting entire Dictionary 
Dict.clear() 
print("\nDeleting Entire Dictionary: ") 
print(Dict) 

Initial Dictionary: 
{5: 'Welcome', 6: 'To', 7: 'Geeks', 'A': {1: 'Geeks', 2: 'For', 3: 'Geeks'}, 'B': {1: 'Geeks', 2: 'Life'}}

Deleting a specific key: 
{5: 'Welcome', 7: 'Geeks', 'A': {1: 'Geeks', 2: 'For', 3: 'Geeks'}, 'B': {1: 'Geeks', 2: 'Life'}}

Deleting a key from Nested Dictionary: 
{5: 'Welcome', 7: 'Geeks', 'A': {1: 'Geeks', 3: 'Geeks'}, 'B': {1: 'Geeks', 2: 'Life'}}

Popping specific element: 
{7: 'Geeks', 'A': {1: 'Geeks', 3: 'Geeks'}, 'B': {1: 'Geeks', 2: 'Life'}}

Pops first element: 
{7: 'Geeks', 'A': {1: 'Geeks', 3: 'Geeks'}}

Deleting Entire Dictionary: 
{}


In [213]:
Dict = { 5 : 'Welcome', 6 : 'To', 7 : 'Geeks', 
        'A' : {1 : 'Geeks', 2 : 'For', 3 : 'Geeks'}, 
        'B' : {1 : 'Geeks', 2 : 'Life'}} 
print("Initial Dictionary: ") 
print(Dict) 

Initial Dictionary: 
{5: 'Welcome', 6: 'To', 7: 'Geeks', 'A': {1: 'Geeks', 2: 'For', 3: 'Geeks'}, 'B': {1: 'Geeks', 2: 'Life'}}


In [214]:
dict.fromkeys()

In [215]:
d = {1: "one", 2: "three"}
d1 = {2: "two"}

# updates the value of key 2
d.update(d1)
print(d)

d1 = {3: "three"}

# adds element with key 3
d.update(d1)
print(d)
d = {'x': 2}

d.update(y = 3, z = 0)
print(d)

{1: 'one', 2: 'two'}
{1: 'one', 2: 'two', 3: 'three'}
{'x': 2, 'y': 3, 'z': 0}


Return Value from get()
The get() method returns:

the value for the specified key if key is in dictionary.  
None if the key is not found and value is not specified.  
value if the key is not found and value is specified.

In [217]:
sales = { 'apple': 2, 'orange': 3, 'grapes': 4 }

print(sales.items())
print(sales.keys())
print(sales.values())

dict_items([('apple', 2), ('orange', 3), ('grapes', 4)])
dict_keys(['apple', 'orange', 'grapes'])
dict_values([2, 3, 4])


setdefault() Parameters
The setdefault() takes maximum of two parameters:

key - key to be searched in the dictionary  
default_value (optional) - key with a value default_value is inserted to the dictionary if key is not in the dictionary.  
If not provided, the default_value will be None.  

pop() Parameters
The pop() method takes two parameters:

key - key which is to be searched for removal  
default - value which is to be returned when the key is not in the dictionary  

In [218]:
person = {'name': 'Phill', 'age': 22, 'salary': 3500.0}

result = person.popitem()
print('person = ',person)
print('Return Value = ',result)

person =  {'name': 'Phill', 'age': 22}
Return Value =  ('salary', 3500.0)


The popitem()

returns an arbitrary element (key, value) pair from the dictionary  
removes an arbitrary element (the same element which is returned) from the dictionary.  

In [230]:
person["name"]

'Phill'

## Arrays

benefits over Python lists, such as: being more compact, faster access in reading and writing items, being more convenient and more efficient.

You see that, in the example above, the data are integers. The array holds and represents any regular data in a structured way.  

However, you should know that, on a structural level, an array is basically nothing but pointers. It’s a combination of a memory address, a data type, a shape, and strides:  

The data pointer indicates the memory address of the first byte in the array,  
The data type or dtype pointer describes the kind of elements that are contained within the array,     
The shape indicates the shape of the array, and
The strides are the number of bytes that should be skipped in memory to go to the next element. If your strides are (10,1), you need to proceed one byte to get to the next column and 10 bytes to locate the next row.

In [283]:
# Make the array `my_array`
my_array = np.array([[1,2,3,4], [5,6,7,8]], dtype=np.int64)

# Print `my_array`
print("my_array", my_array)

# Create an array of ones
############################# watch for the double brackets for ones, and other functions################
print("\nCreate an array of ones \n" ,np.ones((3,4)))

# Create an array of zeros
print("\n Create an array of zeros \n" ,np.zeros((2,3,4),dtype=np.int16))

# Create an array with random values
print("\n Create an array with random values \n" , np.random.random((2,2)))

# Create an empty array
print("\n Create an empty array \n", np.empty((3,2)))

# Create a full array
print("\n Create a full array \n ",np.full((2,2),7))

# Create an array of evenly-spaced values
print("\n Create an array of evenly-spaced values \n ",np.arange(10,25,5))

# Create an array of evenly-spaced values
print("\n Create an array of evenly-spaced values \n ", np.linspace(0,2,9))

"""With np.linspace() and np.arange() you can make arrays of evenly spaced values. The difference between these two 
functions is that the last value of the three that are passed in the code chunk above designates either the step 
value for np.linspace() or a number of samples for np.arange(). What happens in the first is that you want, for 
example, an array of 9 values that lie between 0 and 2. For the latter, you specify that you want an array to 
start at 10 and per steps of 5, generate values for the array that you’re creating."""

my_array [[1 2 3 4]
 [5 6 7 8]]

Create an array of ones 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

 Create an array of zeros 
 [[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]

 Create an array with random values 
 [[0.865925   0.73062537]
 [0.41285225 0.40771274]]

 Create an empty array 
 [[0. 0.]
 [0. 0.]
 [0. 0.]]

 Create a full array 
  [[7 7]
 [7 7]]

 Create an array of evenly-spaced values 
  [10 15 20]

 Create an array of evenly-spaced values 
  [0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


'With np.linspace() and np.arange() you can make arrays of evenly spaced values. The difference between these two \nfunctions is that the last value of the three that are passed in the code chunk above designates either the step \nvalue for np.linspace() or a number of samples for np.arange(). What happens in the first is that you want, for \nexample, an array of 9 values that lie between 0 and 2. For the latter, you specify that you want an array to \nstart at 10 and per steps of 5, generate values for the array that you’re creating.'

In [289]:
my_2d_array = np.arange(9).reshape(3,3)
print(my_2d_array.data)

# Print out the shape of `my_array`
print("Shape" ,my_2d_array.shape)

# Print out the data type of `my_array`
print("dtype",my_2d_array.dtype)

# Print out the stride of `my_array`
print("stride",my_2d_array.strides)

print("dimension",my_array.ndim)

# Print the number of `my_array`'s elements
print("number of elemnets",my_array.size)

# Print information about `my_array`'s memory layout
print("memory layout",my_array.flags)

# Print the length of one array element in bytes
print("length of one array elemnets in bytes",my_array.itemsize)

# Print the total consumed bytes by `my_array`'s elements
print("total number of bytes",my_array.nbytes)
# Print the length of `my_array`
print("len", len(my_array))

# Change the data type of `my_array`
print("change dtype",my_array.astype(float))

Shape (3, 3)
dtype int32
stride (12, 4)
dimension 2
number of elemnets 8
memory layout   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False
length of one array elemnets in bytes 8
total number of bytes 64
len 2
change dtype [[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
total number of bytes 64


In [331]:
a = np.arange(20,32,1).reshape(2,2,3)
a

array([[[20, 21, 22],
        [23, 24, 25]],

       [[26, 27, 28],
        [29, 30, 31]]])

array are indexed row (0,1,2,3) and column as (0,1,2,3) in above case and not each elementwise. so if we use array[row,column] it will give that specific row and column.  
If we use : is to get a value from either row or col, as show below

In [339]:
print(a[0,1,1])
#print(a[:,1:2])
#print(a[a>24])

24


# Formating of Values

In [ ]:
my_string = "Hello, World!"
print(my_string)

Given an integer, , perform the following conditional actions:

If n is odd, print Weird

If n is even and in the inclusive range of 2 to 5, print Not Weird

If n is even and in the inclusive range of 6 to 20, print Weird

If n is even and greater than 20, print Not Weird

In [ ]:
N = int(input())
if (N%2 != 0):
    print("Weird")
elif (N>=2 and N<=5):
    print("Not Weird")
elif(N>=6 and N<=20):
    print("Weird")
elif(N>20):
    print("Not Weird")

Read two integers and print two lines. 
The first line should contain integer division,  // . 
The second line should contain float division,  / .

You don't need to perform any rounding or formatting operations.

In [ ]:
    a = int(input())
    b = int(input())
    print(int(a/b))
    print(a/b)

Read an integer N . For all non-negative integers i<N, print i2. See the sample for details.

In [ ]:
    n = int(input())
    for i in range(n):
     print(i*i)

We add a Leap Day on February 29, almost every four years. The leap day is an extra, or intercalary day and we add it to the shortest month of the year, February. 
In the Gregorian calendar three criteria must be taken into account to identify leap years:

The year can be evenly divided by 4, is a leap year, unless:

    The year can be evenly divided by 100, it is NOT a leap year, unless:

        The year is also evenly divisible by 400. Then it is a leap year.

This means that in the Gregorian calendar, the years 2000 and 2400 are leap years, while 1800, 1900, 2100, 2200, 2300 and 2500 are NOT leap years.Source

Task 
You are given the year, and you have to write a function to check if the year is leap or not.

Note that you have to complete the function and remaining code is given as template.

In [ ]:
def is_leap(year):
    leap = False
    
    if ((year%4 ==0) ):
        leap = True
        if(year%100==0 ):
            leap = False
            if((year%400==0)):
        
                leap = True
    return leap

year = int(input())
print(is_leap(year))


year = int(input())
print(is_leap(year))

Read an integer .

Without using any string methods, try to print the following:
123...N
end in the print statement is used to supress the new line

In [25]:
n = int(input())
for i in range(n):
    print(i+1, end='')

3
123

In [23]:
s =  "HackerRank.com presents Pythonist 2"
print(s.swapcase())

hACKERrANK.COM PRESENTS pYTHONIST 2


In [3]:
t= ["this", "is", "good"]
print("".join([t[i] for i in range(len(t))]))
print("".join(t))

thisisgood
thisisgood


#### String Split and Join

In [35]:
a = "this is a string"
a = a.split(" ") # a is converted to a list of strings. 
print( a)
a = "-".join(a)
print( a)

['this', 'is', 'a', 'string']
this-is-a-string


In [36]:
a = "this is a string"
print("-".join(a.split()))

this-is-a-string


In [47]:
fn = str(input())
ln= str(input())
print("Hello {0} {1}! You just delved into python.".format(fn,ln))

Nit
Ku
Hello Nit Ku ! You just delved into python.


#### String Manipluation

We have seen that lists are mutable (they can be changed), and tuples are immutable (they cannot be changed).

Let's try to understand this with an example.

You are given an immutable string, and you want to make changes to it.
You can access an index by:
    print string[5]
    What if you would like to assign a value?
    string[5] = 'k' 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'str' object does not support item assignment

In [55]:
print("One solution is to convert the string to a list and then change the value.")
string = "abracadabra"
print("before:",string)
l = list(string)
l[5] = 'Y'
string = ''.join(l)
print("after:",string)

print("Another approach is to slice the string and join it back.")
string = string[:5] + "k" + string[6:]
print (string)

One solution is to convert the string to a list and then change the value.
before: abracadabra
after: abracYdabra
Another approach is to slice the string and join it back.
abrackdabra


In [157]:
string = "ininini"
substr = "ini"
print(string.find(substr))
#print(string[string.find(substr)+1:len(string)])

0


In [158]:
l= 0
count= 0
while(l>=0):
    l = string.find(substr,l,len(string))
    #print(l)
    if(l==0):
        l+=1
    if(l>=0):
        count+=1
        string = string[l:len(string)]
        #print(string, count)
print(count)

3


Python any() function. The any() function tests whether any item in the iterable evaluates to True to not. 
It accepts an iterable and returns True, if at least one item in the iterable is true, otherwise, it returns False.

Below functions can can check on a string or at a character level as shown below with a for loop

In [166]:
s = "Th23"
print(s.isalnum())
print(s.isalpha())
print(s.isdigit())
print(s.islower())
print(s.isupper())


True
False
False
False
False


In [167]:
    str = input()
    print (any(c.isalnum()  for c in str))
    print (any(c.isalpha() for c in str))
    print (any(c.isdigit() for c in str))
    print (any(c.islower() for c in str))
    print (any(c.isupper() for c in str))

w2E
True
True
True
True
True


in Python, a string of text can be aligned left, right and center.

.ljust(width)           This method returns a left aligned string of length width.

.center(width)          This method returns a centered string of length width.

.rjust(width)           This method returns a right aligned string of length width.


In [170]:
width = 20
print( 'HackerRank'.ljust(width,'-'))
print( 'HackerRank'.rjust(width,'-'))
print( 'HackerRank'.center(width,'-'))

HackerRank----------
----------HackerRank
-----HackerRank-----


https://www.geeksforgeeks.org/python-format-function/

s – strings

d – decimal integers (base-10)
f – floating point display
c – character
b – binary
o – octal
x – hexadecimal with lowercase letters after 9
X – hexadecimal with uppercase letters after 9
e – exponent notation

In [175]:
number = int(input())

5


In [210]:
width = len("{0:b}".format(number))
for i in range(1, number + 1):
        print("{0:{width}d} {0:{width}o} {0:{width}X} {0:{width}b}".format(i, width=width))

101
1 1 1 1
2 2 2 10
3 3 3 11
4 4 4 100
5 5 5 101


In [215]:
print("Hello {0} {1}, how are you doing. You owe {2:.3f} {3:d}".format("Nitin","Kumar",10000900,2))

Hello Nitin Kumar, how are you doing. You owe 10000900.000 2


If sep is not specified or is None, a different splitting algorithm is applied: runs of consecutive whitespace 
    are regarded as a single separator, and the result will contain no empty strings at the start or end if the 
    string has leading or trailing whitespace. Consequently, splitting an empty string or a string consisting of 
    just whitespace with a None separator returns [].

In [277]:
s = "hello   world  lol"

In [292]:
t = s.split( " ")
print(' '.join([t[i].capitalize() for i in range(len(t))] ))

Hello   World  Lol


In [290]:
"hello   world  lol".split()

['hello', 'world', 'lol']

In [1]:
p = "BANANA"
p = list(p)
vow = ["A","E","I","O","U"]
count_vol = 0
count_cons = 0
vol =[]
con = []
t = []
for i in range(len(p)):
    for j in range(i,len(p)):
        #print("inside j",i,j)
        if(p[i]in vow):
            #vol.append(p[i]+[j])
            vol.append(p[j])
            #print("vol" ,vol)
            count_vol+=1
        else:
            #con.append(p[i]+[j])
            con.append(p[j])
            count_cons+=1
            #print("con",con )

if(count_cons>=count_vol):
    print("Stuart", count_cons)
else:
    print("Kevin", count_vol)   
print("Count of Cont is: {} and Count of Vol is {}" .format(count_cons, count_vol))     

Stuart 12
Count of Cont is: 12 and Count of Vol is 9


In [61]:
num = input()
a = (np.array(num.split(" "),int)).reshape(3,3)
print(a)

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [107]:
k,arr = int(input()),list(map(int, input().split()))

myset = set(arr)
print(myset, arr)
print(sum(myset)*k)
print(sum(arr))
print(((sum(myset)*k)-(sum(arr)))//(k-1))

3
1 1 1 2 2 2 3 3 3 4
{1, 2, 3, 4} [1, 1, 1, 2, 2, 2, 3, 3, 3, 4]
30
22
4


# searching pairs in list or missing pair

In [5]:
ar = [10 ,20 ,20 ,10 ,10 ,30 ,50 ,10 ,20]
count= []
for i in range(len(ar)):
    print([e for j, e in enumerate(ar) if e == ar[i]])

[10, 10, 10, 10]
[20, 20, 20]
[20, 20, 20]
[10, 10, 10, 10]
[10, 10, 10, 10]
[30]
[50]
[10, 10, 10, 10]
[20, 20, 20]


John works at a clothing store. He has a large pile of socks that he must pair by color for sale. Given an array of integers representing the color of each sock, determine how many pairs of socks with matching colors there are.

For example, there are n= 7 socks with colors ar = [1,2,1,2,1,3,2]. There is one pair of color 1  and one of color 2. There are three odd socks left, one of each color. The number of pairs is 2.

In [118]:
pair = 0
s = tuple(set(ar))
for i in range(len(s)):
    c = ar.count(s[i])
    #print("values is {} and count is {}".format(ar[i],c))
    val = c//2
    pair += val
print(pair)

values is 10 and count is 4
values is 20 and count is 3
values is 20 and count is 1
values is 10 and count is 1
3


In [56]:
colors = {}
pairs = 0
for i in range(len(socks)):
    if (socks[i] not in colors):
        colors.update({socks[i]:1})
    else:
        pairs +=1
        colors.pop(socks[i])

In [58]:
colors, pairs

({30: 1, 50: 1, 20: 1}, 3)

In [76]:
strg = list("UDDDUDUU")
strg = list("DDUUDDUDUUUD")

In [77]:
strg

['D', 'D', 'U', 'U', 'D', 'D', 'U', 'D', 'U', 'U', 'U', 'D']

In [80]:
val=0
u=0
d = 0
temp = 0
for i in range(len(strg)):
    if strg[i]=="U":
        u +=1
    else:
        d+=1
    if d>u and temp <1:
        val+=1
        temp +=1
    elif (u>=d):
        temp = 0
val

2

In [357]:
s =  list([0,0, 1, 0, 0, 1, 0])

In [3]:
for i in range(10):
    print(i,i//2, i%2, i/2)

0 0 0 0.0
1 0 1 0.5
2 1 0 1.0
3 1 1 1.5
4 2 0 2.0
5 2 1 2.5
6 3 0 3.0
7 3 1 3.5
8 4 0 4.0
9 4 1 4.5


In [82]:
def minsum(num,k):
    import random as r
    sum=0
    for i in range(k):
        a = r.choice(num)
        ind = num.index(a)
        num.pop(ind)
        num.insert(ind,round(a/2))
        for ii in range(len(num)):
            sum+=num[ii]
        if sum==0:
            sum+=1
    return num, sum

In [83]:
minsum(num,k)

([0, 0, 1, 6, 1, 1, 1, 1, 6, 1, 1, 1, 1, 2, 2, 2, 2, 2, 11, 2], 558)